
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	    <OutputType>Library</OutputType>
		<OutputPath>..\Assemblies</OutputPath>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>CaravanHunting</RootNamespace>
	    <AssemblyName>CaravanHunting</AssemblyName>
		<AssemblyTitle>Diet Filters In Storage</AssemblyTitle>
		<AssemblyVersion>2024.0721.1</AssemblyVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		 <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
 <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\..\..\RimWorldLinux_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\..\RimWorldLinux_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\RimWorldLinux_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\..\RimWorldLinux_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>..\..\..\RimWorldLinux_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
